// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzgfkltvqqznenmevjnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6Z2ZrbHR2cXF6bmVubWV2am53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNzkxODMsImV4cCI6MjA1MzY1NTE4M30.jEciJHymcuCxVdYfyzsrpFoiuZEPdO0No3t7gz664OU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);